/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;

import db.JDBC;
import javax.swing.*;
import java.sql.*;
import java.sql.PreparedStatement;

/**
 *
 * @author kiran
 */
public class admin_signup extends javax.swing.JFrame {

    /**
     * Creates new form admin_signup
     */
    public admin_signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        squt = new javax.swing.JTextField();
        sans = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN SIGNUP PAGE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ADMIN SIGNUP PAGE");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 220, 44));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("NAME");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 145, 112, -1));

        password.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        password.setMaximumSize(null);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 207, 203, -1));

        name.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        name.setMaximumSize(null);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 142, 203, -1));

        squt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        squt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        squt.setMaximumSize(null);
        getContentPane().add(squt, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 269, 203, -1));

        sans.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sans.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sans.setMaximumSize(null);
        getContentPane().add(sans, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 328, 203, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("PASSWORD");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 210, 112, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("S QUT");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 272, 112, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("S ANS");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 331, 112, -1));

        signup.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        signup.setText("SIGNUP");
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 427, 83, -1));

        reset.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 427, 83, -1));

        close.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 427, 83, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jeo_mart_billing_system/walling.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 600, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new admin_signup().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        String uname = name.getText();
        String upword = password.getText();
        String qut = squt.getText();
        String ans = sans.getText();
        
        if(!uname.isEmpty() && !upword.isEmpty() && !qut.isEmpty() && !ans.isEmpty()){
         try(Connection con=JDBC.con();
            PreparedStatement ps= con.prepareStatement("sp_adm_insert ?,?,?,?");){
          
            ps.setString(1, uname);
            ps.setString(2, upword);
            ps.setString(3,qut);
            ps.setString(4, ans);
            
            int a=ps.executeUpdate();
            
            if(a != 0)
            {
                JOptionPane.showMessageDialog(this, "All the data ");
            }
            else{JOptionPane.showMessageDialog(this, "All the data enter");}
            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);

        }
        } else{ JOptionPane.showMessageDialog(this, "Enter All the fields");}
    }//GEN-LAST:event_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sans;
    private javax.swing.JButton signup;
    private javax.swing.JTextField squt;
    // End of variables declaration//GEN-END:variables
}
