/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author kiran
 */
public class bar_code extends javax.swing.JFrame {

    /**
     * Creates new form bar_code
     */
    public bar_code() {
        initComponents();
    }
    
      private BufferedImage createBarcodeImage(String text,int width, int height)throws WriterException{
           BitMatrix bitMatrix =new MultiFormatWriter().encode(text,BarcodeFormat.CODE_128,width,height);
        return MatrixToImageWriter.toBufferedImage(bitMatrix);
      }
         private BufferedImage barcodeImage;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text = new javax.swing.JTextField();
        bar_code = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        textlb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BAR CODE");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("BAR CODE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 118, 34));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("TEXT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 85, 43, -1));

        text.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 82, 154, -1));

        bar_code.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bar_code.setText("BAR CODE");
        bar_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar_codeActionPerformed(evt);
            }
        });
        getContentPane().add(bar_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 396, 101, -1));

        reset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 396, 83, -1));

        close.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 396, 83, -1));

        textlb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(textlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 140, 176, 142));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jeo_mart_billing_system/shine.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new bar_code().setVisible(true);
        
    }//GEN-LAST:event_resetActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void bar_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar_codeActionPerformed
        // TODO add your handling code here:
         String text1=text.getText();
        
        if(text1.isEmpty()){
             JOptionPane.showMessageDialog(this, "PLEASE ENTER TEXT TO GENERATE BAR CODE");
             return;
        }
        try{
            barcodeImage =createBarcodeImage(text1,400,150);
            textlb.setIcon(new ImageIcon(barcodeImage));
            
            
          } catch (Exception e) {
                 JOptionPane.showMessageDialog(this,e);

           }
        
        if(textlb !=null){
             JFileChooser fileChooser=new JFileChooser();
         int userSelection=fileChooser.showOpenDialog(this);
         
           if (userSelection ==JFileChooser.APPROVE_OPTION){
                 File fileToSave=fileChooser.getSelectedFile();
                   try{
                      ImageIO.write(barcodeImage,"png",fileToSave);
                       textlb.setIcon(new ImageIcon(barcodeImage));
            
              JOptionPane.showMessageDialog(this, "BAR CODE SAVED SUCCESSFULLY!");
          } catch (Exception ex) {
                 JOptionPane.showMessageDialog(this,ex);
          }
           
               
           }
        }
        
    }//GEN-LAST:event_bar_codeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bar_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bar_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bar_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bar_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bar_code().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bar_code;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton reset;
    private javax.swing.JTextField text;
    private javax.swing.JLabel textlb;
    // End of variables declaration//GEN-END:variables
}
