/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;


import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;
import javax.mail.*;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.InternetAddress;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.Session;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMultipart;


/**
 *
 * @author kiran
 */
public class email extends javax.swing.JFrame {

    private File selectedFile;

    /**
     * Creates new form email
     */
    public email() {
        initComponents();
    }
        
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        semail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        remail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mess = new javax.swing.JTextArea();
        attach = new javax.swing.JButton();
        send = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        sub = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMAIL PAGE");
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buyerAdd.png"))); // NOI18N
        jLabel1.setText("EMAIL PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 16, 158, 41));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("SENDER E-MAIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 93, 111, -1));

        semail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(semail, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 90, 182, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 120, 85, -1));

        password.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 117, 182, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("RECIVER E-MAIL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 153, 111, -1));

        remail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        remail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remailActionPerformed(evt);
            }
        });
        getContentPane().add(remail, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 150, 182, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("SUBJECT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 189, 74, -1));

        mess.setColumns(20);
        mess.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        mess.setLineWrap(true);
        mess.setRows(5);
        mess.setWrapStyleWord(true);
        jScrollPane1.setViewportView(mess);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 240, 182, 93));

        attach.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        attach.setText("ATTACH");
        attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachActionPerformed(evt);
            }
        });
        getContentPane().add(attach, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 117, 83, -1));

        send.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        send.setText("SEND");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 210, 83, -1));

        reset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 408, 83, -1));

        close.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 408, 83, -1));
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 189, 182, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("MESSAGE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 253, 74, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vijay.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void remailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remailActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
           new email().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser=new JFileChooser();
         int returnValue=fileChooser.showOpenDialog(this);
         if (returnValue==JFileChooser.APPROVE_OPTION){
             selectedFile = fileChooser.getSelectedFile();
             JOptionPane.showMessageDialog(this, "Selected file : "+selectedFile.getName());
         }
               
         
    }//GEN-LAST:event_attachActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
         String fromEmail=semail.getText();
         String pass=password.getText();
         String toEmail=remail.getText();
         String subject=sub.getText();
         String message=mess.getText();

        String email=remail.getText();
        String regex="^[a-zA-Z0-9]-(?:\\.[a-z]+)*@(?:\\.[a-z]+)+[a-z]{2,3}$";
        Pattern pattern=Pattern.compile(regex);
        Matcher matcher=pattern.matcher(email);
                if(matcher.matches()){
                       JOptionPane.showMessageDialog(this,"EMAIL MATCHED");
                }else{
                       JOptionPane.showMessageDialog(this,"EMAIL not MATCHED");
                }
                
                if(selectedFile==null){
                    JOptionPane.showMessageDialog(this,"PLEASE SELECT A FILE TO ATTACH");
                    return;
                }
                
                Properties props=new Properties();
                props.put("mail.smtp.host", "smtp.gmail.com");
                props.put("mail.smtp.port", "587");
                props.put("mail.smtp.auth", "true"); 
                props.put("mail.smtp.starttls.enable", "true");
                
                
           
           Session session =Session.getInstance(props, new javax.mail.Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication(fromEmail,pass);
                }
                    
           });
           
           try{
              Message msg = new MimeMessage(session);

               
              
              msg.setFrom(new InternetAddress(fromEmail));
              msg.addRecipient(Message.RecipientType.TO,new InternetAddress(fromEmail));
              msg.setSubject(subject);
              
              BodyPart messageBodyPart=new MimeBodyPart();
              messageBodyPart.setText(message);
              
              Multipart multipart=new MimeMultipart();
              multipart.addBodyPart(messageBodyPart);
              
              messageBodyPart=new MimeBodyPart();
              DataSource source=new FileDataSource(selectedFile);
              messageBodyPart.setDataHandler(new DataHandler(source));
              messageBodyPart.setFileName(selectedFile.getName());
              multipart.addBodyPart(messageBodyPart);
              
              msg.setContent(multipart);
              
              Transport.send(msg);
              
               JOptionPane.showMessageDialog(this, "EMAIL SEND SUCCESSFULLY WITH ATTACHMENT!");
           } catch ( MessagingException e) {
                 JOptionPane.showMessageDialog(this, e.getMessage());
           }
          
               
           
        
          
    
                     
    
                      
                
    }//GEN-LAST:event_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new email().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attach;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mess;
    private javax.swing.JTextField password;
    private javax.swing.JTextField remail;
    private javax.swing.JButton reset;
    private javax.swing.JTextField semail;
    private javax.swing.JButton send;
    private javax.swing.JTextField sub;
    // End of variables declaration//GEN-END:variables

 

 
}
