/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.*;


/**
 *
 * @author kiran
 */
public class otp_email extends javax.swing.JFrame {

    /**
     * Creates new form otp_email
     */
    public otp_email() {
        initComponents();
    }

    private void sendOTPEmail (String recipientEmail,String otp){
          String senderEmail=semail.getText();
          String senderPassword=password.getText();
         
         
           Properties props=new Properties();
                props.put("mail.smtp.host", "smtp.gmail.com");
                props.put("mail.smtp.port", "587");
                props.put("mail.smtp.auth", "true"); 
                props.put("mail.smtp.starttls.enable", "true");
                
                
           
           Session session =Session.getInstance(props, new javax.mail.Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication(senderEmail,senderPassword);
                }
                    
           });
           try{
            Message message = new MimeMessage(session);

              message.setFrom(new InternetAddress(senderEmail));
              message.addRecipient(Message.RecipientType.TO,new InternetAddress(recipientEmail));
              message.setSubject("YOUR OTP CODE");
              
            
              message.setText("Your OTP CODE: "+otp);
             
              Transport.send(message);
              
               JOptionPane.showMessageDialog(this, "OTP SEND SUCCESSFULLY!");
           } catch (Exception e) {
                 JOptionPane.showMessageDialog(this,e);

           }
        
    }
    private String generateOTP(){
        int otp1=(int)(Math.random()*900000)+100000;
        return String.valueOf(otp1);
        
    }
    private String generatedOTP;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        semail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        remail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        otp = new javax.swing.JTextField();
        otp_send = new javax.swing.JButton();
        match = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OTP THROUGH EMAIL ");
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("OTP THROUGH EMAIL ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 35, 227, 29));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("SENDER E-MAIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 134, -1, -1));

        semail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(semail, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 131, 141, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 167, 80, -1));

        password.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 164, 141, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("RECIVER E-MAIL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 206, -1, -1));

        remail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(remail, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 203, 141, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("OTP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 245, 57, -1));

        otp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 242, 141, -1));

        otp_send.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        otp_send.setText("OTP SEND");
        otp_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otp_sendActionPerformed(evt);
            }
        });
        getContentPane().add(otp_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 391, 100, -1));

        match.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        match.setText("MATCH");
        match.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchActionPerformed(evt);
            }
        });
        getContentPane().add(match, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 391, 83, -1));

        reset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 391, 83, -1));

        close.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 391, 83, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jeo_mart_billing_system/waterfal.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
           this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
          new otp_email().setVisible(true);
      
    }//GEN-LAST:event_resetActionPerformed

    private void otp_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otp_sendActionPerformed
        // TODO add your handling code here:
          String em=remail.getText();
        String regex="^[a-zA-Z0-9]-(?:\\.[a-z]+)*@(?:\\.[a-z]+)+[a-z]{2,3}$";
        Pattern pattern=Pattern.compile(regex);
        Matcher matcher=pattern.matcher(em);
                if(matcher.matches()){
                       JOptionPane.showMessageDialog(this,"VALID EMAIL");
                }else{
                       JOptionPane.showMessageDialog(this,"IN-VALID EMAIL");
                }
                if(!em.isEmpty()){
                    generatedOTP=generateOTP();
                    sendOTPEmail(em,generatedOTP); 
                     JOptionPane.showMessageDialog(this,"OTP SEND TO: "+em);
                }else{
                     JOptionPane.showMessageDialog(this,"PLEASE ENTER A VALID EMAIL");
                }
    }//GEN-LAST:event_otp_sendActionPerformed

    private void matchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchActionPerformed
        // TODO add your handling code here:
         String enteredOTP=otp.getText();
         if(enteredOTP.equals(generatedOTP)){
                JOptionPane.showMessageDialog(this,"OTP verified successfully  ");
                 new main_page().setVisible(true);
             
             
         } else{
               JOptionPane.showMessageDialog(this,"INVALID OTP . please try again!");
             
         }
        
        
    }//GEN-LAST:event_matchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(otp_email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(otp_email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(otp_email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(otp_email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new otp_email().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton match;
    private javax.swing.JTextField otp;
    private javax.swing.JButton otp_send;
    private javax.swing.JTextField password;
    private javax.swing.JTextField remail;
    private javax.swing.JButton reset;
    private javax.swing.JTextField semail;
    // End of variables declaration//GEN-END:variables
}
