/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;

import javax.swing.*;
import java.sql.*;
import db.JDBC;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kiran
 */
public class product_details extends javax.swing.JFrame {

    /**
     * Creates new form product_details
     */
    public product_details() {
        initComponents();
    }
      public static String decrypt (String encryptedData,String secretKey) throws Exception{
        Cipher cipher=Cipher.getInstance("AES");
        SecretKeySpec secretKeySpec=new SecretKeySpec(secretKey.getBytes(),"AES");
        cipher.init(Cipher.DECRYPT_MODE,secretKeySpec );
        byte[] decodedBytes=Base64.getDecoder().decode(encryptedData);
        byte[] decryptedBytes=cipher.doFinal(decodedBytes);
        return new String(decryptedBytes);
        
    }
    private final String SECRET_KEY="1234567890123456";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        details = new javax.swing.JButton();
        csv_file = new javax.swing.JButton();
        print = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRODUCT DETAILS");
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BUYER DETAILS.png"))); // NOI18N
        jLabel1.setText("PRODUCT DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 20, 225, 36));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "NAME", "RATE", "DISCRIPTION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 68, -1, 296));

        details.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        details.setText("DETAILS");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });
        getContentPane().add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 426, -1, -1));

        csv_file.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        csv_file.setText("CSVFILE");
        csv_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csv_fileActionPerformed(evt);
            }
        });
        getContentPane().add(csv_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 426, 83, -1));

        print.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 426, 83, -1));

        close.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 426, 83, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/walling_1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 610, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
         try{
            table.print(JTable.PrintMode.NORMAL);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
                 
        }
    }//GEN-LAST:event_printActionPerformed

    private void csv_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csv_fileActionPerformed
        // TODO add your handling code here:
        
         JFileChooser fileChooser=new JFileChooser();
         int userSelection=fileChooser.showOpenDialog(this);
         
           if (userSelection ==JFileChooser.APPROVE_OPTION){
                 File fileToSave=fileChooser.getSelectedFile();
               
                 String filePath =fileToSave.getAbsolutePath();
                 if(!filePath.endsWith(".csv")){
                     filePath +=".csv";
                 }
                     
                 
                 try(BufferedWriter writer =new BufferedWriter(new FileWriter(filePath))){
                     
                     for(int i=0;i<table.getColumnCount();i++){
                         writer.write(table.getColumnName(i));
                         if(i<table.getColumnCount() -1){
                               writer.write(",");
                         }
                         
                     }
                        writer.newLine();
                        
                        
                          for(int row=0;row<table.getRowCount();row++){
                               for(int col=0;col<table.getColumnCount();col++){
                                     writer.write(table.getValueAt(row, col).toString());
                                         if(col<table.getColumnCount() -1){
                               writer.write(",");
                         }
                         
                     }
                        writer.newLine();
                              
                          }
                          JOptionPane.showMessageDialog(this, "Data exported to csv  successfully");
                      
                 }
                 catch(Exception e){
                       JOptionPane.showMessageDialog(this,e);
                 }
                     
              
                 }
           
    }//GEN-LAST:event_csv_fileActionPerformed

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
        // TODO add your handling code here:
        
          try(Connection con=JDBC.con();
            PreparedStatement ps= con.prepareStatement("sp_ins_get");){
         
            ResultSet rs=ps.executeQuery();
            
            DefaultTableModel m=(DefaultTableModel) table.getModel();
            while(rs.next())
                {
            
              
           m.addRow(new Object[]{rs.getString("pid"),rs.getString("pname"),decrypt(rs.getString("prate"),SECRET_KEY),rs.getString("pdis")});
                }

           
              
              
              
            }
            
//            else{JOptionPane.showMessageDialog(this, "enter correct SECURITY ANSWER");}
            
            
            
            
  
         catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
         }

    }//GEN-LAST:event_detailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton csv_file;
    private javax.swing.JButton details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
