/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;

import db.JDBC;
import javax.swing.*;
import java.sql.*;
import java.sql.PreparedStatement;

/**
 *
 * @author kiran
 */
public class reset_password extends javax.swing.JFrame {

    /**
     * Creates new form reset_password
     */
    public reset_password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        admin_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        new_password = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        old_password = new javax.swing.JTextField();
        confirm_password = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        security_question = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        security_answer = new javax.swing.JTextField();
        reset_password = new javax.swing.JButton();
        forget_password = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel4.setText("jLabel2");

        jTextField3.setText("jTextField1");

        jLabel6.setText("jLabel2");

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RESET AND FORGET PASSWORD");
        setMaximumSize(new java.awt.Dimension(550, 550));
        setMinimumSize(new java.awt.Dimension(550, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("RESET AND FORGET PASSWORD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 238, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ADMIN NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 129, 125, -1));

        admin_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        admin_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_nameActionPerformed(evt);
            }
        });
        getContentPane().add(admin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 126, 148, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("OLD PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 174, 125, -1));

        new_password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(new_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 211, 148, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("NEW PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 214, 125, -1));

        old_password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(old_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 171, 148, -1));

        confirm_password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 262, 148, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 265, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("SECURITY QUESTION");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 313, 159, -1));

        security_question.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(security_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 310, 148, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("SECURITY ANSWER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 363, 142, -1));

        security_answer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        security_answer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                security_answerKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                security_answerKeyTyped(evt);
            }
        });
        getContentPane().add(security_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 360, 148, -1));

        reset_password.setBackground(new java.awt.Color(153, 153, 255));
        reset_password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset_password.setText("RESET PASSWORD");
        reset_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(reset_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 421, 142, -1));

        forget_password.setBackground(new java.awt.Color(204, 255, 204));
        forget_password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        forget_password.setText("FORGET PASSWORD");
        forget_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forget_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(forget_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 421, -1, -1));

        reset.setBackground(new java.awt.Color(153, 51, 255));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 488, 83, -1));

        close.setBackground(new java.awt.Color(204, 51, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 488, 83, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jeo_mart_billing_system/wall2.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void forget_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forget_passwordActionPerformed
        // TODO add your handling code here:
          String uname = admin_name.getText();
     
        
         try(Connection con=JDBC.con();
            PreparedStatement ps= con.prepareStatement("select squt from admtbl  where name=?");){
          
            ps.setString(1, uname);
          
           
            ResultSet rs=ps.executeQuery();
            
            if(rs.next())
            {
                security_question.setText(rs.getString("squt"));
                JOptionPane.showMessageDialog(this, "SECURITY QUESTION TAKEN FROM DATA BASE");
            }
            else{JOptionPane.showMessageDialog(this, "enter correct user name");}
            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);

        }
        
            
                   
    }//GEN-LAST:event_forget_passwordActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void security_answerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_security_answerKeyReleased
        // TODO add your handling code here:
         String ans = security_answer.getText();
     
        
         try(Connection con=JDBC.con();
            PreparedStatement ps= con.prepareStatement("select password from admtbl  where sans=?");){
          
            ps.setString(1, ans);
          
           
            ResultSet rs=ps.executeQuery();
            
            if(rs.next())
            {
                old_password.setText(rs.getString("password"));
                JOptionPane.showMessageDialog(this, "SECURITY ANSWER TAKEN FROM DATA BASE");
            }
//            else{JOptionPane.showMessageDialog(this, "enter correct SECURITY ANSWER");}
            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);

        }
        
         
        
    }//GEN-LAST:event_security_answerKeyReleased

    private void security_answerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_security_answerKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_security_answerKeyTyped

    private void reset_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_passwordActionPerformed
        // TODO add your handling code here:
        
        
        
        String uname = admin_name.getText();
        String opwd = old_password.getText();
        String npwd = new_password.getText();
        String cpwd = confirm_password.getText();
        
       if(!opwd.equals(npwd) && npwd.equals(cpwd) && !uname.isEmpty()  && !opwd.isEmpty()){
         try(Connection con=JDBC.con();
            PreparedStatement ps= con.prepareStatement("sp_update_pwd ?,?");){
            
          
            ps.setString(1, uname);
            ps.setString(2,npwd);
          
            int a=ps.executeUpdate();
            
            if(a != 0)
            {
                JOptionPane.showMessageDialog(this, "NEW PASSWORD  CHANGED ");
                this.dispose();
//             new admin_login().setVisible(false);
            }
            else{JOptionPane.showMessageDialog(rootPane, "ENTER THE FIELD CORRECTLY");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }
        }
    }//GEN-LAST:event_reset_passwordActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
          new reset_password().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void admin_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reset_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admin_name;
    private javax.swing.JButton close;
    private javax.swing.JTextField confirm_password;
    private javax.swing.JButton forget_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField new_password;
    private javax.swing.JTextField old_password;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset_password;
    private javax.swing.JTextField security_answer;
    private javax.swing.JTextField security_question;
    // End of variables declaration//GEN-END:variables

   
}
