/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;

/**
 *
 * @author kiran
 */
public class utilities extends javax.swing.JFrame {

    /**
     * Creates new form utilities
     */
    public utilities() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        email = new javax.swing.JButton();
        otp = new javax.swing.JButton();
        qr_code = new javax.swing.JButton();
        bar_code = new javax.swing.JButton();
        bar_chart = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" UTILITIES PAGE");
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 39, 144, -1));

        email.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        email.setText("EMAIL");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 99, 95, -1));

        otp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        otp.setText("OTP");
        otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpActionPerformed(evt);
            }
        });
        getContentPane().add(otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 161, 95, -1));

        qr_code.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        qr_code.setText("QR CODE");
        qr_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qr_codeActionPerformed(evt);
            }
        });
        getContentPane().add(qr_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 231, 95, -1));

        bar_code.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bar_code.setText("BAR CODE");
        bar_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar_codeActionPerformed(evt);
            }
        });
        getContentPane().add(bar_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 316, 102, -1));

        bar_chart.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bar_chart.setText("BAR CHART");
        bar_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar_chartActionPerformed(evt);
            }
        });
        getContentPane().add(bar_chart, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PERSON.png"))); // NOI18N
        jLabel2.setText(" UTILITIES PAGE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 28, 198, 37));

        close.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallpaper5.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
          new email().setVisible(true);
    }//GEN-LAST:event_emailActionPerformed

    private void otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpActionPerformed
        // TODO add your handling code here:
         new otp_email().setVisible(true);
    }//GEN-LAST:event_otpActionPerformed

    private void qr_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qr_codeActionPerformed
        // TODO add your handling code here:
            new qr_code().setVisible(true);
    }//GEN-LAST:event_qr_codeActionPerformed

    private void bar_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar_codeActionPerformed
        // TODO add your handling code here:
         new bar_code().setVisible(true);
    }//GEN-LAST:event_bar_codeActionPerformed

    private void bar_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar_chartActionPerformed
        // TODO add your handling code here:
         new bar_chart().setVisible(true);
    }//GEN-LAST:event_bar_chartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new utilities().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bar_chart;
    private javax.swing.JButton bar_code;
    private javax.swing.JButton close;
    private javax.swing.JButton email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton otp;
    private javax.swing.JButton qr_code;
    // End of variables declaration//GEN-END:variables
}
